name: build-and-push-pages
on:
  push:
    branches:
    - main
jobs:
  needs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v3
    - uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    # TODO: Replace this with a dependency to a proper "Build Package" job
    #       Dist is needed to get version number
    - name: Build package
      run: |
        pip install build
        python -m build
    # END TODO

    - name: Building documentation
      run: |
        pip install -r pydrumscore/requirements.txt

        sphinx-apidoc --module-first -o docs/source/ pydrumscore/ *test -e
        sphinx-build docs public -b dirhtml

    - name: github pages deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: public
