name: Build and Publish Documentation
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v3
    - uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    # didn't need to change anything here, but had to add sphinx.ext.githubpages
    # to my conf.py extensions list. that fixes the broken uploads
    - name: Building documentation
      run: |
        pip install sphinx
        sphinx-apidoc  --module-first -o docs/source/ pydrumscore/

    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        requirements_path: 'pydrumscore/requirements.txt'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages